default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: appointments_API_development
test:
  <<: *default
  database: appointments_API_test
production:
  <<: *default
  database: appointments_API_production
  username: appointments_API
  password: <%= ENV['APPOINTMENTS_API_DATABASE_PASSWORD'] %>